export const quotes = {
    financial: [
      { word: 'Income', quote: 'A steady income is the foundation of financial stability.' },
      { word: 'Income', quote: 'Managing your income wisely today secures your tomorrow.' },
      { word: 'Income', quote: 'Income isn’t just money; it’s a tool for crafting your future.' },
      { word: 'Income', quote: 'Your income can either be a seed for growth or a burden of debt.' },
      { word: 'Income', quote: 'Diversify your income to create multiple streams of financial security.' },
      { word: 'Income', quote: 'Income should be earned, not just received.' },
      { word: 'Income', quote: 'Financial freedom starts with a reliable income.' },
      { word: 'Income', quote: 'Income is not just about earning; it’s about managing and growing.' },
      { word: 'Income', quote: 'Maximize your income potential through continuous learning and improvement.' },
      { word: 'Income', quote: 'A well-managed income is the key to a stress-free life.' },
      { word: 'Income', quote: 'Invest in your skills to boost your income over time.' },
      { word: 'Income', quote: 'A balanced income can lead to a balanced life.' },
      { word: 'Income', quote: 'Secure your income first, then plan for your expenditures.' },
      { word: 'Income', quote: 'Your income can reflect your value, dedication, and hard work.' },
      { word: 'Income', quote: 'Smart income management can turn dreams into reality.' },
      { word: 'Income', quote: 'Income growth should be a part of your financial strategy.' },
      { word: 'Income', quote: 'Income is the reward for your effort, skill, and perseverance.' },
      { word: 'Income', quote: 'Transform your income into wealth through strategic investments.' },
      { word: 'Income', quote: 'Income provides the means to achieve your goals and ambitions.' },
      { word: 'Income', quote: 'Building a steady income stream is the first step towards financial independence.' }
    ],
    dayToDayChallenges: [
      { word: 'Appointments', quote: 'Appointments are the anchors of a well-organized schedule.' },
      { word: 'Appointments', quote: 'Never underestimate the power of keeping your appointments.' },
      { word: 'Appointments', quote: 'Every appointment is an opportunity to progress and achieve.' },
      { word: 'Appointments', quote: 'Timely appointments lead to timely results.' },
      { word: 'Appointments', quote: 'Respect your appointments; they reflect your commitment.' },
      { word: 'Appointments', quote: 'Keeping appointments shows professionalism and reliability.' },
      { word: 'Appointments', quote: 'Appointments are the building blocks of a productive day.' },
      { word: 'Appointments', quote: 'Effective appointment management is key to reducing stress.' },
      { word: 'Appointments', quote: 'Your appointments mirror your priorities and discipline.' },
      { word: 'Appointments', quote: 'Appointments are opportunities wrapped in time slots.' },
      { word: 'Appointments', quote: 'Every missed appointment is a missed opportunity.' },
      { word: 'Appointments', quote: 'Appointments keep the chaos of life in check.' },
      { word: 'Appointments', quote: 'Respect your appointments to gain respect in return.' },
      { word: 'Appointments', quote: 'Appointments create a roadmap for achieving your goals.' },
      { word: 'Appointments', quote: 'A well-scheduled appointment is a well-kept promise.' },
      { word: 'Appointments', quote: 'Appointments are commitments you make to yourself and others.' },
      { word: 'Appointments', quote: 'Success often hinges on the appointments you keep.' },
      { word: 'Appointments', quote: 'Strategically planned appointments enhance efficiency.' },
      { word: 'Appointments', quote: 'Mastering your appointments is mastering your time.' },
      { word: 'Appointments', quote: 'Appointments guide the flow of your daily activities.' }
    ]
  };
  